title: ' '
theme: jekyll-theme-minimal
show_downloads: true
layouts_dir: docs/_layouts
logo: docs/logo_color_stripe_solo_logo-1.png
google_site_verification: XqjgDDzQlNamaGft-wYZtx565x3YrDmJa-e2nsku1fU
plugins:
  - jekyll-seo-tag
